[package]
name = "RNAsieve"
version = "0.1.0"
edition = "2024"

[dependencies]
bio = "1"
clap = { version = "4.4", features = ["derive"] }
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
needletail = "0.5"
anyhow = "1.0"
flate2 = "1.0"
